# Production environment configuration for the Quantum and AI Arbitration Project

# General settings
app:
  name: "Quantum and AI Arbitration"
  version: "1.0.0"
  debug: false  # Disable debug mode in production

# Database configuration
database:
  uri: "postgresql://username:password@localhost:5432/arbitration_db"  # Use PostgreSQL for production
  max_connections: 50  # Maximum number of database connections

# Quantum settings
quantum:
  backend: "ibmq_qasm_simulator"  # Use IBM Quantum backend for production
  shots: 2048  # Number of shots for quantum simulations

# AI Model settings
ai:
  model_path: "./models/production_model.pkl"  # Path to the production model
  threshold: 0.7  # Threshold for predictions

# Logging configuration
logging:
  level: "INFO"  # Set logging level to INFO for production
  file: "./logs/production.log"  # Log file path
  format: "%(asctime)s - %(levelname)s - %(message)s"  # Log format

# Fraud detection settings
fraud_detection:
  model_path: "./models/fraud_detection_model_prod.pkl"  # Path to the fraud detection model

# Risk assessment settings
risk_assessment:
  model_path: "./models/risk_assessment_model_prod.pkl"  # Path to the risk assessment model

# Additional settings can be added as needed
